server:
  port: 8080

spring:

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}

    consumer:
      group_id: orchestrator-group
      auto-offset-reset: latest


loggin:
  level:
    org:
      apache:
        kafka: OFF